# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/Serious_sam_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(0, 0, 650, 450))
        self.map_label.setObjectName("map_label")
        self.map_cneter_latitude_label = QtWidgets.QLabel(self.centralwidget)
        self.map_cneter_latitude_label.setGeometry(QtCore.QRect(0, 460, 161, 17))
        self.map_cneter_latitude_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_cneter_latitude_label.setObjectName("map_cneter_latitude_label")
        self.map_cneter_longitude_label = QtWidgets.QLabel(self.centralwidget)
        self.map_cneter_longitude_label.setGeometry(QtCore.QRect(170, 460, 161, 17))
        self.map_cneter_longitude_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_cneter_longitude_label.setObjectName("map_cneter_longitude_label")
        self.map_center_latitude_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_center_latitude_line_edit.setGeometry(QtCore.QRect(0, 480, 151, 20))
        self.map_center_latitude_line_edit.setObjectName("map_center_latitude_line_edit")
        self.map_center_longitude_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_center_longitude_line_edit.setGeometry(QtCore.QRect(170, 480, 151, 20))
        self.map_center_longitude_line_edit.setObjectName("map_center_longitude_line_edit")
        self.map_type_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.map_type_list_widget.setGeometry(QtCore.QRect(340, 480, 256, 21))
        self.map_type_list_widget.setObjectName("map_type_list_widget")
        self.map_type_label = QtWidgets.QLabel(self.centralwidget)
        self.map_type_label.setGeometry(QtCore.QRect(340, 460, 251, 17))
        self.map_type_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_type_label.setObjectName("map_type_label")
        self.map_spn_latitude_label = QtWidgets.QLabel(self.centralwidget)
        self.map_spn_latitude_label.setGeometry(QtCore.QRect(0, 510, 161, 17))
        self.map_spn_latitude_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_spn_latitude_label.setObjectName("map_spn_latitude_label")
        self.map_spn_longitude_label = QtWidgets.QLabel(self.centralwidget)
        self.map_spn_longitude_label.setGeometry(QtCore.QRect(170, 510, 161, 17))
        self.map_spn_longitude_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_spn_longitude_label.setObjectName("map_spn_longitude_label")
        self.map_spn_latitude_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_spn_latitude_line_edit.setGeometry(QtCore.QRect(0, 530, 151, 20))
        self.map_spn_latitude_line_edit.setObjectName("map_spn_latitude_line_edit")
        self.map_spn_longitude_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_spn_longitude_line_edit.setGeometry(QtCore.QRect(170, 530, 151, 20))
        self.map_spn_longitude_line_edit.setObjectName("map_spn_longitude_line_edit")
        self.map_size_X_label = QtWidgets.QLabel(self.centralwidget)
        self.map_size_X_label.setGeometry(QtCore.QRect(0, 560, 161, 17))
        self.map_size_X_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_size_X_label.setObjectName("map_size_X_label")
        self.map_size_X_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_size_X_line_edit.setGeometry(QtCore.QRect(0, 580, 61, 20))
        self.map_size_X_line_edit.setObjectName("map_size_X_line_edit")
        self.map_size_Y_label = QtWidgets.QLabel(self.centralwidget)
        self.map_size_Y_label.setGeometry(QtCore.QRect(170, 560, 161, 17))
        self.map_size_Y_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_size_Y_label.setObjectName("map_size_Y_label")
        self.map_size_Y_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_size_Y_line_edit.setGeometry(QtCore.QRect(170, 580, 61, 20))
        self.map_size_Y_line_edit.setObjectName("map_size_Y_line_edit")
        self.map_objects_scale_label = QtWidgets.QLabel(self.centralwidget)
        self.map_objects_scale_label.setGeometry(QtCore.QRect(340, 560, 211, 17))
        self.map_objects_scale_label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.map_objects_scale_label.setObjectName("map_objects_scale_label")
        self.map_objects_scale_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.map_objects_scale_line_edit.setGeometry(QtCore.QRect(340, 580, 61, 20))
        self.map_objects_scale_line_edit.setObjectName("map_objects_scale_line_edit")
        self.update_map_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_map_push_button.setGeometry(QtCore.QRect(128, 620, 201, 25))
        self.update_map_push_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_map_push_button.setFlat(False)
        self.update_map_push_button.setObjectName("update_map_push_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anthrax Simulator"))
        self.map_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ef2929;\">Awating data input </span></p></body></html>"))
        self.map_cneter_latitude_label.setText(_translate("MainWindow", "Широта центра карты"))
        self.map_cneter_longitude_label.setText(_translate("MainWindow", "Долгота центра карты"))
        self.map_center_latitude_line_edit.setText(_translate("MainWindow", "44.949997"))
        self.map_center_longitude_line_edit.setText(_translate("MainWindow", "34.097528"))
        self.map_type_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Тип карты</p></body></html>"))
        self.map_spn_latitude_label.setText(_translate("MainWindow", "<html><head/><body><p>Ширина  карты (°)</p></body></html>"))
        self.map_spn_longitude_label.setText(_translate("MainWindow", "Длина карты (°)"))
        self.map_spn_latitude_line_edit.setText(_translate("MainWindow", "0.01"))
        self.map_spn_longitude_line_edit.setText(_translate("MainWindow", "0.01"))
        self.map_size_X_label.setText(_translate("MainWindow", "<html><head/><body><p>Ширина изображения</p><p><br/></p></body></html>"))
        self.map_size_X_line_edit.setText(_translate("MainWindow", "650"))
        self.map_size_Y_label.setText(_translate("MainWindow", "<html><head/><body><p>Длина изображения</p><p><br/></p></body></html>"))
        self.map_size_Y_line_edit.setText(_translate("MainWindow", "450"))
        self.map_objects_scale_label.setText(_translate("MainWindow", "<html><head/><body><p>Коэф-т увеличения объектов</p></body></html>"))
        self.map_objects_scale_line_edit.setText(_translate("MainWindow", "1.0"))
        self.update_map_push_button.setText(_translate("MainWindow", "UpDate"))

