/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author myfamily
 */
import java.io.*;
import javax.swing.JOptionPane;
public class ClientMainFrame extends javax.swing.JFrame {
    public static void infoBox(String infoMessage, String titleBar)
        {
            JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
        }
    /**
     * Creates new form ClientMainFrame
     */
    public ClientMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServerIPlabel = new javax.swing.JLabel();
        ServerIPtextField = new javax.swing.JTextField();
        ServerPortlabel = new javax.swing.JLabel();
        ServerPorttextField = new javax.swing.JTextField();
        IntervalStartlabel = new javax.swing.JLabel();
        IntervalStarttextField = new javax.swing.JTextField();
        IntervalEndlabel = new javax.swing.JLabel();
        IntervalEndtextField = new javax.swing.JTextField();
        Steplabel = new javax.swing.JLabel();
        SteptextField = new javax.swing.JTextField();
        Divisorslabel = new javax.swing.JLabel();
        DivisorstextField = new javax.swing.JTextField();
        AmountOfFindedlabel = new javax.swing.JLabel();
        AmountOfFindedtextField = new javax.swing.JTextField();
        ElapsedTimelabel = new javax.swing.JLabel();
        ElapsedTimetextField = new javax.swing.JTextField();
        Connectbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsoletextArea = new javax.swing.JTextArea();
        Consolelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculaction Client");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ServerIPlabel.setText("Server IP:");

        ServerIPtextField.setText("127.0.0.1");

        ServerPortlabel.setText("Server Port");

        ServerPorttextField.setText("9898");

        IntervalStartlabel.setText("Start");

        IntervalStarttextField.setText("0");

        IntervalEndlabel.setText("End");

        IntervalEndtextField.setText("1");

        Steplabel.setText("Step");
        Steplabel.setToolTipText("");

        SteptextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SteptextField.setText("1000");

        Divisorslabel.setText("Divisors");

        DivisorstextField.setText("11,13,17");
        DivisorstextField.setToolTipText("");

        AmountOfFindedlabel.setText("Amount of finded");

        AmountOfFindedtextField.setText("0");

        ElapsedTimelabel.setText("Elapsed time (ms)");

        ElapsedTimetextField.setText("0");

        Connectbutton.setText("C O N N E C T");
        Connectbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Connectbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        Connectbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectbuttonMouseClicked(evt);
            }
        });

        ConsoletextArea.setColumns(20);
        ConsoletextArea.setRows(5);
        jScrollPane1.setViewportView(ConsoletextArea);

        Consolelabel.setText("Console");
        Consolelabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Steplabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IntervalStartlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IntervalStarttextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServerIPtextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(ServerIPlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServerPorttextField)
                            .addComponent(ServerPortlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IntervalEndlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Divisorslabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IntervalEndtextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SteptextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DivisorstextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AmountOfFindedtextField)
                            .addComponent(AmountOfFindedlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ElapsedTimelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ElapsedTimetextField)))
                    .addComponent(Connectbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consolelabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServerIPlabel)
                    .addComponent(ServerPortlabel)
                    .addComponent(Consolelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ServerIPtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ServerPorttextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IntervalStartlabel)
                            .addComponent(IntervalEndlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IntervalStarttextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IntervalEndtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Steplabel)
                            .addComponent(Divisorslabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SteptextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DivisorstextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AmountOfFindedlabel)
                            .addComponent(ElapsedTimelabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AmountOfFindedtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ElapsedTimetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Connectbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConnectbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectbuttonMouseClicked
        // TODO add your handling code here:
        this.ConsoletextArea.setText(null);
        CalculClient client = new CalculClient(this.ServerIPtextField.getText(),
                                Integer.parseInt(this.ServerPorttextField.getText()),
                                this.ConsoletextArea);
        try
        {
            client.ConnectToServer();
            this.IntervalStarttextField.setText(Integer.toString(client.start));
            this.IntervalEndtextField.setText(Integer.toString(client.end));
            this.DivisorstextField.setText(client.denoms.toString());
            this.SteptextField.setText(Integer.toString(client.end - client.start));
            
            client.findNums();
            
            this.AmountOfFindedtextField.setText(Integer.toString(client.AmountOfFinded));
            
            client.sendResponseAndClose();
            
            this.ElapsedTimetextField.setText(Long.toString(client.elapsedTime) );
        }
        catch (IOException ex)
        {
            ClientMainFrame.infoBox("Something went horribly wrong while trying to reach server" +
                    ex.getMessage(),
                    ex.toString());
        }
        
    }//GEN-LAST:event_ConnectbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountOfFindedlabel;
    private javax.swing.JTextField AmountOfFindedtextField;
    private javax.swing.JButton Connectbutton;
    private javax.swing.JLabel Consolelabel;
    private javax.swing.JTextArea ConsoletextArea;
    private javax.swing.JLabel Divisorslabel;
    private javax.swing.JTextField DivisorstextField;
    private javax.swing.JLabel ElapsedTimelabel;
    private javax.swing.JTextField ElapsedTimetextField;
    private javax.swing.JLabel IntervalEndlabel;
    private javax.swing.JTextField IntervalEndtextField;
    private javax.swing.JLabel IntervalStartlabel;
    private javax.swing.JTextField IntervalStarttextField;
    private javax.swing.JLabel ServerIPlabel;
    private javax.swing.JTextField ServerIPtextField;
    private javax.swing.JLabel ServerPortlabel;
    private javax.swing.JTextField ServerPorttextField;
    private javax.swing.JLabel Steplabel;
    private javax.swing.JTextField SteptextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
